services:
  - type: web
    name: proposly-api
    env: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Secret
        sync: false
      - key: Jwt__Issuer
        value: proposly
      - key: Jwt__Audience
        value: proposly-users
      - key: Smtp__Host
        sync: false
      - key: Smtp__Port
        sync: false
      - key: Smtp__UseSsl
        sync: false
      - key: Smtp__Username
        sync: false
      - key: Smtp__Password
        sync: false
      - key: Smtp__SenderEmail
        sync: false
      - key: Smtp__SenderName
        value: Proposly
      - key: AppUrl
        sync: false
      - key: Cors__AllowedOrigin
        sync: false

