using Proposly.Domain.OfferManagement.Enums;

namespace Proposly.Application.OfferManagement.Responses;

public record OfferSummaryResponse(
    Guid Id,
    Guid ClientId,
    string ClientName,
    string Title,
    OfferStatus Status,
    decimal Subtotal,
    decimal? DiscountPercent,
    decimal DiscountAmount,
    decimal VatBase,
    decimal VatAmount,
    decimal Total,
    decimal VatRate,
    string VatLabel,
    string Currency,
    DateOnly? ValidUntil,
    DateTime CreatedAt);

public record OfferDetailResponse(
    Guid Id,
    Guid ClientId,
    string ClientName,
    string? ClientContactPerson,
    string? ClientEmail,
    string? ClientPhone,
    string? ClientStreet,
    string? ClientCity,
    string? ClientPostalCode,
    string? ClientCountry,
    string? ClientVatNumber,
    string CompanyName,
    string? CompanyEmail,
    string? CompanyPhone,
    string? CompanyStreet,
    string? CompanyCity,
    string? CompanyPostalCode,
    string Title,
    string? Notes,
    OfferStatus Status,
    decimal Subtotal,
    decimal? DiscountPercent,
    decimal DiscountAmount,
    decimal VatBase,
    decimal VatAmount,
    decimal Total,
    decimal VatRate,
    string VatType,
    string VatLabel,
    string? VatNote,
    bool IsVatExempt,
    string Currency,
    DateOnly? ValidUntil,
    DateTime? SentAt,
    DateTime CreatedAt,
    IReadOnlyList<OfferItemResponse> Items);

public record OfferItemResponse(
    Guid Id,
    string Description,
    decimal Quantity,
    decimal UnitPrice,
    decimal LineTotal,
    string Currency);
